# Server settings 
server:
  port: 80
  context-path: /

# DATASOURCE 
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
  freemarker:
    suffix: .html
  profiles:
    active: dev
  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# MyBatis
mybatis:
  mapperLocations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.zhangpan.model
  configuration:
    call-setters-on-nulls: true
    use-generated-keys: true
    map-underscore-to-camel-case: true
        
#分页
pagehelper:
  auto-dialect: true
  reasonable: true
  support-methods-arguments: true
  params: count
  
logging:
  path: logs
  level: 
    com.zhangpan.dao: debug
    org.mybatis: debug