# Server settings 
server:
  port: 8080
  context-path: /

# DATASOURCE 
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
  freemarker:
    suffix: .html

# MyBatis
mybatis:
  mapperLocations: classpath:mapper/*Mapper.xml
  config-location: classpath:config/mybatis-configuration.xml
#  type-aliases-package: com.zhangpan.model
#  configuration:
#    map-underscore-to-camel-case: true
#    call-setters-on-nulls: true
