# Server settings 
server:
  port: 80
  context-path: /

# DATASOURCE 
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
  freemarker:
    suffix: .html
  profiles:
    active: dev
  mail:
    host: smtp.126.com
    username: zpzxcvb@126.com
    password: 527517062
    properties:
      smtp: 
        auth: true
#文件上传
  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
#redis
  redis:
    database: 0
    host: localhost
    port: 6379
    password: 12345
    pool:
      max-active: 8
      max-idle: 8
      max-wait: -1
# MyBatis
mybatis:
  mapperLocations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.zhangpan.model
  configuration:
    call-setters-on-nulls: true
    use-generated-keys: true
    map-underscore-to-camel-case: true
        
#分页
pagehelper:
  auto-dialect: true
  reasonable: true
  support-methods-arguments: true
  params: count
  
logging:
#  path: logs
  level: 
    com.zhangpan.dao: debug
    org.mybatis: debug
  